name: enigma2-plugins build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build enigma2-plugins
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        gcc: [11,12,13]
        python: ['3.10','3.11','3.12']
    steps:
      - name: Install prerequisites
        run: |
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get -q update
          sudo apt remove -y libunwind-14-dev
          sudo apt-get install -y g++-${{ matrix.gcc }} build-essential autoconf autotools-dev gettext python${{ matrix.python }}-dev libntirpc-dev
          
      - uses: actions/checkout@v3
        with:
          ref: 'master'

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Build plugins, gcc-${{ matrix.gcc }}, python ${{ matrix.python }}
        env:
          CC: "gcc-${{ matrix.gcc }}"
          CXX: "g++-${{ matrix.gcc }}"
        run: |
          pip3 install six
          sed -i '/PKG_CHECK_MODULES(ENIGMA2, enigma2)/d' ./configure.ac
          sed -i '/PKG_CHECK_MODULES(LIBCRYPTO, libcrypto)/d' ./configure.ac
          sudo cp /usr/include/tirpc/rpc/* /usr/include/rpc/
          sudo cp /usr/include/tirpc/netconfig.h /usr/include/
          autoreconf -i
          ./configure --without-debug --with-po
          make
          rm -rf ./subsdownloader2
          python -m compileall .
